version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./go:/go/src/app
    tty: true
    depends_on:
      - postgres
    command: go run main.go

  postgres:
    build: ./postgres/
    ports:
      - "3300:3300"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d