version: '3'
services:
  db:
    build: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init:/docker-entrypoint-initdb.d